CREATE TABLE IF NOT EXISTS MANAGER (
             ID INTEGER AUTO_INCREMENT,
             ACCOUNT VARCHAR (255) NOT NULL,
             NAME VARCHAR (255) NOT NULL,
             PASSWORD VARCHAR (255) NOT NULL,
             PRIMARY KEY (ID),
             UNIQUE (ACCOUNT)
);